spring:
  application:
    name: week1-day1-backend
  profile:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pixida_study
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
